/*
 * Pydio Cells Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.pydio.cells.openapi.model;

import com.google.gson.Gson;
import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.pydio.cells.openapi.JSON;

import java.io.IOException;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Map.Entry;
import java.util.Objects;
import java.util.Set;

/**
 * InstallInstallConfig
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-04-15T17:35:14.400736592+02:00[Europe/Berlin]")
public class InstallInstallConfig {
  public static final String SERIALIZED_NAME_CHECK_RESULTS = "CheckResults";
  @SerializedName(SERIALIZED_NAME_CHECK_RESULTS)
  private List<InstallCheckResult> checkResults;

  public static final String SERIALIZED_NAME_DOCUMENTS_D_S_N = "DocumentsDSN";
  @SerializedName(SERIALIZED_NAME_DOCUMENTS_D_S_N)
  private String documentsDSN;

  public static final String SERIALIZED_NAME_PROXY_CONFIG = "ProxyConfig";
  @SerializedName(SERIALIZED_NAME_PROXY_CONFIG)
  private InstallProxyConfig proxyConfig;

  public static final String SERIALIZED_NAME_USE_DOCUMENTS_D_S_N = "UseDocumentsDSN";
  @SerializedName(SERIALIZED_NAME_USE_DOCUMENTS_D_S_N)
  private Boolean useDocumentsDSN;

  public static final String SERIALIZED_NAME_DB_CONNECTION_TYPE = "dbConnectionType";
  @SerializedName(SERIALIZED_NAME_DB_CONNECTION_TYPE)
  private String dbConnectionType;

  public static final String SERIALIZED_NAME_DB_MANUAL_D_S_N = "dbManualDSN";
  @SerializedName(SERIALIZED_NAME_DB_MANUAL_D_S_N)
  private String dbManualDSN;

  public static final String SERIALIZED_NAME_DB_SOCKET_FILE = "dbSocketFile";
  @SerializedName(SERIALIZED_NAME_DB_SOCKET_FILE)
  private String dbSocketFile;

  public static final String SERIALIZED_NAME_DB_SOCKET_NAME = "dbSocketName";
  @SerializedName(SERIALIZED_NAME_DB_SOCKET_NAME)
  private String dbSocketName;

  public static final String SERIALIZED_NAME_DB_SOCKET_PASSWORD = "dbSocketPassword";
  @SerializedName(SERIALIZED_NAME_DB_SOCKET_PASSWORD)
  private String dbSocketPassword;

  public static final String SERIALIZED_NAME_DB_SOCKET_USER = "dbSocketUser";
  @SerializedName(SERIALIZED_NAME_DB_SOCKET_USER)
  private String dbSocketUser;

  public static final String SERIALIZED_NAME_DB_T_C_P_HOSTNAME = "dbTCPHostname";
  @SerializedName(SERIALIZED_NAME_DB_T_C_P_HOSTNAME)
  private String dbTCPHostname;

  public static final String SERIALIZED_NAME_DB_T_C_P_NAME = "dbTCPName";
  @SerializedName(SERIALIZED_NAME_DB_T_C_P_NAME)
  private String dbTCPName;

  public static final String SERIALIZED_NAME_DB_T_C_P_PASSWORD = "dbTCPPassword";
  @SerializedName(SERIALIZED_NAME_DB_T_C_P_PASSWORD)
  private String dbTCPPassword;

  public static final String SERIALIZED_NAME_DB_T_C_P_PORT = "dbTCPPort";
  @SerializedName(SERIALIZED_NAME_DB_T_C_P_PORT)
  private String dbTCPPort;

  public static final String SERIALIZED_NAME_DB_T_C_P_USER = "dbTCPUser";
  @SerializedName(SERIALIZED_NAME_DB_T_C_P_USER)
  private String dbTCPUser;

  public static final String SERIALIZED_NAME_DB_USE_DEFAULTS = "dbUseDefaults";
  @SerializedName(SERIALIZED_NAME_DB_USE_DEFAULTS)
  private Boolean dbUseDefaults;

  public static final String SERIALIZED_NAME_DS_FOLDER = "dsFolder";
  @SerializedName(SERIALIZED_NAME_DS_FOLDER)
  private String dsFolder;

  public static final String SERIALIZED_NAME_DS_NAME = "dsName";
  @SerializedName(SERIALIZED_NAME_DS_NAME)
  private String dsName;

  public static final String SERIALIZED_NAME_DS_PORT = "dsPort";
  @SerializedName(SERIALIZED_NAME_DS_PORT)
  private String dsPort;

  public static final String SERIALIZED_NAME_DS_S3_API_KEY = "dsS3ApiKey";
  @SerializedName(SERIALIZED_NAME_DS_S3_API_KEY)
  private String dsS3ApiKey;

  public static final String SERIALIZED_NAME_DS_S3_API_SECRET = "dsS3ApiSecret";
  @SerializedName(SERIALIZED_NAME_DS_S3_API_SECRET)
  private String dsS3ApiSecret;

  public static final String SERIALIZED_NAME_DS_S3_BUCKET_BINARIES = "dsS3BucketBinaries";
  @SerializedName(SERIALIZED_NAME_DS_S3_BUCKET_BINARIES)
  private String dsS3BucketBinaries;

  public static final String SERIALIZED_NAME_DS_S3_BUCKET_CELLS = "dsS3BucketCells";
  @SerializedName(SERIALIZED_NAME_DS_S3_BUCKET_CELLS)
  private String dsS3BucketCells;

  public static final String SERIALIZED_NAME_DS_S3_BUCKET_DEFAULT = "dsS3BucketDefault";
  @SerializedName(SERIALIZED_NAME_DS_S3_BUCKET_DEFAULT)
  private String dsS3BucketDefault;

  public static final String SERIALIZED_NAME_DS_S3_BUCKET_PERSONAL = "dsS3BucketPersonal";
  @SerializedName(SERIALIZED_NAME_DS_S3_BUCKET_PERSONAL)
  private String dsS3BucketPersonal;

  public static final String SERIALIZED_NAME_DS_S3_BUCKET_THUMBS = "dsS3BucketThumbs";
  @SerializedName(SERIALIZED_NAME_DS_S3_BUCKET_THUMBS)
  private String dsS3BucketThumbs;

  public static final String SERIALIZED_NAME_DS_S3_BUCKET_VERSIONS = "dsS3BucketVersions";
  @SerializedName(SERIALIZED_NAME_DS_S3_BUCKET_VERSIONS)
  private String dsS3BucketVersions;

  public static final String SERIALIZED_NAME_DS_S3_CUSTOM = "dsS3Custom";
  @SerializedName(SERIALIZED_NAME_DS_S3_CUSTOM)
  private String dsS3Custom;

  public static final String SERIALIZED_NAME_DS_S3_CUSTOM_REGION = "dsS3CustomRegion";
  @SerializedName(SERIALIZED_NAME_DS_S3_CUSTOM_REGION)
  private String dsS3CustomRegion;

  public static final String SERIALIZED_NAME_DS_TYPE = "dsType";
  @SerializedName(SERIALIZED_NAME_DS_TYPE)
  private String dsType;

  public static final String SERIALIZED_NAME_FRONTEND_APPLICATION_TITLE = "frontendApplicationTitle";
  @SerializedName(SERIALIZED_NAME_FRONTEND_APPLICATION_TITLE)
  private String frontendApplicationTitle;

  public static final String SERIALIZED_NAME_FRONTEND_DEFAULT_LANGUAGE = "frontendDefaultLanguage";
  @SerializedName(SERIALIZED_NAME_FRONTEND_DEFAULT_LANGUAGE)
  private String frontendDefaultLanguage;

  public static final String SERIALIZED_NAME_FRONTEND_HOSTS = "frontendHosts";
  @SerializedName(SERIALIZED_NAME_FRONTEND_HOSTS)
  private String frontendHosts;

  public static final String SERIALIZED_NAME_FRONTEND_LOGIN = "frontendLogin";
  @SerializedName(SERIALIZED_NAME_FRONTEND_LOGIN)
  private String frontendLogin;

  public static final String SERIALIZED_NAME_FRONTEND_PASSWORD = "frontendPassword";
  @SerializedName(SERIALIZED_NAME_FRONTEND_PASSWORD)
  private String frontendPassword;

  public static final String SERIALIZED_NAME_FRONTEND_REPEAT_PASSWORD = "frontendRepeatPassword";
  @SerializedName(SERIALIZED_NAME_FRONTEND_REPEAT_PASSWORD)
  private String frontendRepeatPassword;

  public static final String SERIALIZED_NAME_INTERNAL_URL = "internalUrl";
  @SerializedName(SERIALIZED_NAME_INTERNAL_URL)
  private String internalUrl;

  public static final String SERIALIZED_NAME_LICENSE_REQUIRED = "licenseRequired";
  @SerializedName(SERIALIZED_NAME_LICENSE_REQUIRED)
  private Boolean licenseRequired;

  public static final String SERIALIZED_NAME_LICENSE_STRING = "licenseString";
  @SerializedName(SERIALIZED_NAME_LICENSE_STRING)
  private String licenseString;

  public InstallInstallConfig() {
  }

  public InstallInstallConfig checkResults(List<InstallCheckResult> checkResults) {
    
    this.checkResults = checkResults;
    return this;
  }

  public InstallInstallConfig addCheckResultsItem(InstallCheckResult checkResultsItem) {
    if (this.checkResults == null) {
      this.checkResults = new ArrayList<>();
    }
    this.checkResults.add(checkResultsItem);
    return this;
  }

   /**
   * Get checkResults
   * @return checkResults
  **/
  @javax.annotation.Nullable

  public List<InstallCheckResult> getCheckResults() {
    return checkResults;
  }


  public void setCheckResults(List<InstallCheckResult> checkResults) {
    this.checkResults = checkResults;
  }


  public InstallInstallConfig documentsDSN(String documentsDSN) {
    
    this.documentsDSN = documentsDSN;
    return this;
  }

   /**
   * Get documentsDSN
   * @return documentsDSN
  **/
  @javax.annotation.Nullable

  public String getDocumentsDSN() {
    return documentsDSN;
  }


  public void setDocumentsDSN(String documentsDSN) {
    this.documentsDSN = documentsDSN;
  }


  public InstallInstallConfig proxyConfig(InstallProxyConfig proxyConfig) {
    
    this.proxyConfig = proxyConfig;
    return this;
  }

   /**
   * Get proxyConfig
   * @return proxyConfig
  **/
  @javax.annotation.Nullable

  public InstallProxyConfig getProxyConfig() {
    return proxyConfig;
  }


  public void setProxyConfig(InstallProxyConfig proxyConfig) {
    this.proxyConfig = proxyConfig;
  }


  public InstallInstallConfig useDocumentsDSN(Boolean useDocumentsDSN) {
    
    this.useDocumentsDSN = useDocumentsDSN;
    return this;
  }

   /**
   * Get useDocumentsDSN
   * @return useDocumentsDSN
  **/
  @javax.annotation.Nullable

  public Boolean getUseDocumentsDSN() {
    return useDocumentsDSN;
  }


  public void setUseDocumentsDSN(Boolean useDocumentsDSN) {
    this.useDocumentsDSN = useDocumentsDSN;
  }


  public InstallInstallConfig dbConnectionType(String dbConnectionType) {
    
    this.dbConnectionType = dbConnectionType;
    return this;
  }

   /**
   * Get dbConnectionType
   * @return dbConnectionType
  **/
  @javax.annotation.Nullable

  public String getDbConnectionType() {
    return dbConnectionType;
  }


  public void setDbConnectionType(String dbConnectionType) {
    this.dbConnectionType = dbConnectionType;
  }


  public InstallInstallConfig dbManualDSN(String dbManualDSN) {
    
    this.dbManualDSN = dbManualDSN;
    return this;
  }

   /**
   * Get dbManualDSN
   * @return dbManualDSN
  **/
  @javax.annotation.Nullable

  public String getDbManualDSN() {
    return dbManualDSN;
  }


  public void setDbManualDSN(String dbManualDSN) {
    this.dbManualDSN = dbManualDSN;
  }


  public InstallInstallConfig dbSocketFile(String dbSocketFile) {
    
    this.dbSocketFile = dbSocketFile;
    return this;
  }

   /**
   * Get dbSocketFile
   * @return dbSocketFile
  **/
  @javax.annotation.Nullable

  public String getDbSocketFile() {
    return dbSocketFile;
  }


  public void setDbSocketFile(String dbSocketFile) {
    this.dbSocketFile = dbSocketFile;
  }


  public InstallInstallConfig dbSocketName(String dbSocketName) {
    
    this.dbSocketName = dbSocketName;
    return this;
  }

   /**
   * Get dbSocketName
   * @return dbSocketName
  **/
  @javax.annotation.Nullable

  public String getDbSocketName() {
    return dbSocketName;
  }


  public void setDbSocketName(String dbSocketName) {
    this.dbSocketName = dbSocketName;
  }


  public InstallInstallConfig dbSocketPassword(String dbSocketPassword) {
    
    this.dbSocketPassword = dbSocketPassword;
    return this;
  }

   /**
   * Get dbSocketPassword
   * @return dbSocketPassword
  **/
  @javax.annotation.Nullable

  public String getDbSocketPassword() {
    return dbSocketPassword;
  }


  public void setDbSocketPassword(String dbSocketPassword) {
    this.dbSocketPassword = dbSocketPassword;
  }


  public InstallInstallConfig dbSocketUser(String dbSocketUser) {
    
    this.dbSocketUser = dbSocketUser;
    return this;
  }

   /**
   * Get dbSocketUser
   * @return dbSocketUser
  **/
  @javax.annotation.Nullable

  public String getDbSocketUser() {
    return dbSocketUser;
  }


  public void setDbSocketUser(String dbSocketUser) {
    this.dbSocketUser = dbSocketUser;
  }


  public InstallInstallConfig dbTCPHostname(String dbTCPHostname) {
    
    this.dbTCPHostname = dbTCPHostname;
    return this;
  }

   /**
   * Get dbTCPHostname
   * @return dbTCPHostname
  **/
  @javax.annotation.Nullable

  public String getDbTCPHostname() {
    return dbTCPHostname;
  }


  public void setDbTCPHostname(String dbTCPHostname) {
    this.dbTCPHostname = dbTCPHostname;
  }


  public InstallInstallConfig dbTCPName(String dbTCPName) {
    
    this.dbTCPName = dbTCPName;
    return this;
  }

   /**
   * Get dbTCPName
   * @return dbTCPName
  **/
  @javax.annotation.Nullable

  public String getDbTCPName() {
    return dbTCPName;
  }


  public void setDbTCPName(String dbTCPName) {
    this.dbTCPName = dbTCPName;
  }


  public InstallInstallConfig dbTCPPassword(String dbTCPPassword) {
    
    this.dbTCPPassword = dbTCPPassword;
    return this;
  }

   /**
   * Get dbTCPPassword
   * @return dbTCPPassword
  **/
  @javax.annotation.Nullable

  public String getDbTCPPassword() {
    return dbTCPPassword;
  }


  public void setDbTCPPassword(String dbTCPPassword) {
    this.dbTCPPassword = dbTCPPassword;
  }


  public InstallInstallConfig dbTCPPort(String dbTCPPort) {
    
    this.dbTCPPort = dbTCPPort;
    return this;
  }

   /**
   * Get dbTCPPort
   * @return dbTCPPort
  **/
  @javax.annotation.Nullable

  public String getDbTCPPort() {
    return dbTCPPort;
  }


  public void setDbTCPPort(String dbTCPPort) {
    this.dbTCPPort = dbTCPPort;
  }


  public InstallInstallConfig dbTCPUser(String dbTCPUser) {
    
    this.dbTCPUser = dbTCPUser;
    return this;
  }

   /**
   * Get dbTCPUser
   * @return dbTCPUser
  **/
  @javax.annotation.Nullable

  public String getDbTCPUser() {
    return dbTCPUser;
  }


  public void setDbTCPUser(String dbTCPUser) {
    this.dbTCPUser = dbTCPUser;
  }


  public InstallInstallConfig dbUseDefaults(Boolean dbUseDefaults) {
    
    this.dbUseDefaults = dbUseDefaults;
    return this;
  }

   /**
   * Get dbUseDefaults
   * @return dbUseDefaults
  **/
  @javax.annotation.Nullable

  public Boolean getDbUseDefaults() {
    return dbUseDefaults;
  }


  public void setDbUseDefaults(Boolean dbUseDefaults) {
    this.dbUseDefaults = dbUseDefaults;
  }


  public InstallInstallConfig dsFolder(String dsFolder) {
    
    this.dsFolder = dsFolder;
    return this;
  }

   /**
   * Get dsFolder
   * @return dsFolder
  **/
  @javax.annotation.Nullable

  public String getDsFolder() {
    return dsFolder;
  }


  public void setDsFolder(String dsFolder) {
    this.dsFolder = dsFolder;
  }


  public InstallInstallConfig dsName(String dsName) {
    
    this.dsName = dsName;
    return this;
  }

   /**
   * Get dsName
   * @return dsName
  **/
  @javax.annotation.Nullable

  public String getDsName() {
    return dsName;
  }


  public void setDsName(String dsName) {
    this.dsName = dsName;
  }


  public InstallInstallConfig dsPort(String dsPort) {
    
    this.dsPort = dsPort;
    return this;
  }

   /**
   * Get dsPort
   * @return dsPort
  **/
  @javax.annotation.Nullable

  public String getDsPort() {
    return dsPort;
  }


  public void setDsPort(String dsPort) {
    this.dsPort = dsPort;
  }


  public InstallInstallConfig dsS3ApiKey(String dsS3ApiKey) {
    
    this.dsS3ApiKey = dsS3ApiKey;
    return this;
  }

   /**
   * Get dsS3ApiKey
   * @return dsS3ApiKey
  **/
  @javax.annotation.Nullable

  public String getDsS3ApiKey() {
    return dsS3ApiKey;
  }


  public void setDsS3ApiKey(String dsS3ApiKey) {
    this.dsS3ApiKey = dsS3ApiKey;
  }


  public InstallInstallConfig dsS3ApiSecret(String dsS3ApiSecret) {
    
    this.dsS3ApiSecret = dsS3ApiSecret;
    return this;
  }

   /**
   * Get dsS3ApiSecret
   * @return dsS3ApiSecret
  **/
  @javax.annotation.Nullable

  public String getDsS3ApiSecret() {
    return dsS3ApiSecret;
  }


  public void setDsS3ApiSecret(String dsS3ApiSecret) {
    this.dsS3ApiSecret = dsS3ApiSecret;
  }


  public InstallInstallConfig dsS3BucketBinaries(String dsS3BucketBinaries) {
    
    this.dsS3BucketBinaries = dsS3BucketBinaries;
    return this;
  }

   /**
   * Get dsS3BucketBinaries
   * @return dsS3BucketBinaries
  **/
  @javax.annotation.Nullable

  public String getDsS3BucketBinaries() {
    return dsS3BucketBinaries;
  }


  public void setDsS3BucketBinaries(String dsS3BucketBinaries) {
    this.dsS3BucketBinaries = dsS3BucketBinaries;
  }


  public InstallInstallConfig dsS3BucketCells(String dsS3BucketCells) {
    
    this.dsS3BucketCells = dsS3BucketCells;
    return this;
  }

   /**
   * Get dsS3BucketCells
   * @return dsS3BucketCells
  **/
  @javax.annotation.Nullable

  public String getDsS3BucketCells() {
    return dsS3BucketCells;
  }


  public void setDsS3BucketCells(String dsS3BucketCells) {
    this.dsS3BucketCells = dsS3BucketCells;
  }


  public InstallInstallConfig dsS3BucketDefault(String dsS3BucketDefault) {
    
    this.dsS3BucketDefault = dsS3BucketDefault;
    return this;
  }

   /**
   * Get dsS3BucketDefault
   * @return dsS3BucketDefault
  **/
  @javax.annotation.Nullable

  public String getDsS3BucketDefault() {
    return dsS3BucketDefault;
  }


  public void setDsS3BucketDefault(String dsS3BucketDefault) {
    this.dsS3BucketDefault = dsS3BucketDefault;
  }


  public InstallInstallConfig dsS3BucketPersonal(String dsS3BucketPersonal) {
    
    this.dsS3BucketPersonal = dsS3BucketPersonal;
    return this;
  }

   /**
   * Get dsS3BucketPersonal
   * @return dsS3BucketPersonal
  **/
  @javax.annotation.Nullable

  public String getDsS3BucketPersonal() {
    return dsS3BucketPersonal;
  }


  public void setDsS3BucketPersonal(String dsS3BucketPersonal) {
    this.dsS3BucketPersonal = dsS3BucketPersonal;
  }


  public InstallInstallConfig dsS3BucketThumbs(String dsS3BucketThumbs) {
    
    this.dsS3BucketThumbs = dsS3BucketThumbs;
    return this;
  }

   /**
   * Get dsS3BucketThumbs
   * @return dsS3BucketThumbs
  **/
  @javax.annotation.Nullable

  public String getDsS3BucketThumbs() {
    return dsS3BucketThumbs;
  }


  public void setDsS3BucketThumbs(String dsS3BucketThumbs) {
    this.dsS3BucketThumbs = dsS3BucketThumbs;
  }


  public InstallInstallConfig dsS3BucketVersions(String dsS3BucketVersions) {
    
    this.dsS3BucketVersions = dsS3BucketVersions;
    return this;
  }

   /**
   * Get dsS3BucketVersions
   * @return dsS3BucketVersions
  **/
  @javax.annotation.Nullable

  public String getDsS3BucketVersions() {
    return dsS3BucketVersions;
  }


  public void setDsS3BucketVersions(String dsS3BucketVersions) {
    this.dsS3BucketVersions = dsS3BucketVersions;
  }


  public InstallInstallConfig dsS3Custom(String dsS3Custom) {
    
    this.dsS3Custom = dsS3Custom;
    return this;
  }

   /**
   * Get dsS3Custom
   * @return dsS3Custom
  **/
  @javax.annotation.Nullable

  public String getDsS3Custom() {
    return dsS3Custom;
  }


  public void setDsS3Custom(String dsS3Custom) {
    this.dsS3Custom = dsS3Custom;
  }


  public InstallInstallConfig dsS3CustomRegion(String dsS3CustomRegion) {
    
    this.dsS3CustomRegion = dsS3CustomRegion;
    return this;
  }

   /**
   * Get dsS3CustomRegion
   * @return dsS3CustomRegion
  **/
  @javax.annotation.Nullable

  public String getDsS3CustomRegion() {
    return dsS3CustomRegion;
  }


  public void setDsS3CustomRegion(String dsS3CustomRegion) {
    this.dsS3CustomRegion = dsS3CustomRegion;
  }


  public InstallInstallConfig dsType(String dsType) {
    
    this.dsType = dsType;
    return this;
  }

   /**
   * Get dsType
   * @return dsType
  **/
  @javax.annotation.Nullable

  public String getDsType() {
    return dsType;
  }


  public void setDsType(String dsType) {
    this.dsType = dsType;
  }


  public InstallInstallConfig frontendApplicationTitle(String frontendApplicationTitle) {
    
    this.frontendApplicationTitle = frontendApplicationTitle;
    return this;
  }

   /**
   * Get frontendApplicationTitle
   * @return frontendApplicationTitle
  **/
  @javax.annotation.Nullable

  public String getFrontendApplicationTitle() {
    return frontendApplicationTitle;
  }


  public void setFrontendApplicationTitle(String frontendApplicationTitle) {
    this.frontendApplicationTitle = frontendApplicationTitle;
  }


  public InstallInstallConfig frontendDefaultLanguage(String frontendDefaultLanguage) {
    
    this.frontendDefaultLanguage = frontendDefaultLanguage;
    return this;
  }

   /**
   * Get frontendDefaultLanguage
   * @return frontendDefaultLanguage
  **/
  @javax.annotation.Nullable

  public String getFrontendDefaultLanguage() {
    return frontendDefaultLanguage;
  }


  public void setFrontendDefaultLanguage(String frontendDefaultLanguage) {
    this.frontendDefaultLanguage = frontendDefaultLanguage;
  }


  public InstallInstallConfig frontendHosts(String frontendHosts) {
    
    this.frontendHosts = frontendHosts;
    return this;
  }

   /**
   * Get frontendHosts
   * @return frontendHosts
  **/
  @javax.annotation.Nullable

  public String getFrontendHosts() {
    return frontendHosts;
  }


  public void setFrontendHosts(String frontendHosts) {
    this.frontendHosts = frontendHosts;
  }


  public InstallInstallConfig frontendLogin(String frontendLogin) {
    
    this.frontendLogin = frontendLogin;
    return this;
  }

   /**
   * Get frontendLogin
   * @return frontendLogin
  **/
  @javax.annotation.Nullable

  public String getFrontendLogin() {
    return frontendLogin;
  }


  public void setFrontendLogin(String frontendLogin) {
    this.frontendLogin = frontendLogin;
  }


  public InstallInstallConfig frontendPassword(String frontendPassword) {
    
    this.frontendPassword = frontendPassword;
    return this;
  }

   /**
   * Get frontendPassword
   * @return frontendPassword
  **/
  @javax.annotation.Nullable

  public String getFrontendPassword() {
    return frontendPassword;
  }


  public void setFrontendPassword(String frontendPassword) {
    this.frontendPassword = frontendPassword;
  }


  public InstallInstallConfig frontendRepeatPassword(String frontendRepeatPassword) {
    
    this.frontendRepeatPassword = frontendRepeatPassword;
    return this;
  }

   /**
   * Get frontendRepeatPassword
   * @return frontendRepeatPassword
  **/
  @javax.annotation.Nullable

  public String getFrontendRepeatPassword() {
    return frontendRepeatPassword;
  }


  public void setFrontendRepeatPassword(String frontendRepeatPassword) {
    this.frontendRepeatPassword = frontendRepeatPassword;
  }


  public InstallInstallConfig internalUrl(String internalUrl) {
    
    this.internalUrl = internalUrl;
    return this;
  }

   /**
   * Get internalUrl
   * @return internalUrl
  **/
  @javax.annotation.Nullable

  public String getInternalUrl() {
    return internalUrl;
  }


  public void setInternalUrl(String internalUrl) {
    this.internalUrl = internalUrl;
  }


  public InstallInstallConfig licenseRequired(Boolean licenseRequired) {
    
    this.licenseRequired = licenseRequired;
    return this;
  }

   /**
   * Get licenseRequired
   * @return licenseRequired
  **/
  @javax.annotation.Nullable

  public Boolean getLicenseRequired() {
    return licenseRequired;
  }


  public void setLicenseRequired(Boolean licenseRequired) {
    this.licenseRequired = licenseRequired;
  }


  public InstallInstallConfig licenseString(String licenseString) {
    
    this.licenseString = licenseString;
    return this;
  }

   /**
   * Get licenseString
   * @return licenseString
  **/
  @javax.annotation.Nullable

  public String getLicenseString() {
    return licenseString;
  }


  public void setLicenseString(String licenseString) {
    this.licenseString = licenseString;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InstallInstallConfig installInstallConfig = (InstallInstallConfig) o;
    return Objects.equals(this.checkResults, installInstallConfig.checkResults) &&
        Objects.equals(this.documentsDSN, installInstallConfig.documentsDSN) &&
        Objects.equals(this.proxyConfig, installInstallConfig.proxyConfig) &&
        Objects.equals(this.useDocumentsDSN, installInstallConfig.useDocumentsDSN) &&
        Objects.equals(this.dbConnectionType, installInstallConfig.dbConnectionType) &&
        Objects.equals(this.dbManualDSN, installInstallConfig.dbManualDSN) &&
        Objects.equals(this.dbSocketFile, installInstallConfig.dbSocketFile) &&
        Objects.equals(this.dbSocketName, installInstallConfig.dbSocketName) &&
        Objects.equals(this.dbSocketPassword, installInstallConfig.dbSocketPassword) &&
        Objects.equals(this.dbSocketUser, installInstallConfig.dbSocketUser) &&
        Objects.equals(this.dbTCPHostname, installInstallConfig.dbTCPHostname) &&
        Objects.equals(this.dbTCPName, installInstallConfig.dbTCPName) &&
        Objects.equals(this.dbTCPPassword, installInstallConfig.dbTCPPassword) &&
        Objects.equals(this.dbTCPPort, installInstallConfig.dbTCPPort) &&
        Objects.equals(this.dbTCPUser, installInstallConfig.dbTCPUser) &&
        Objects.equals(this.dbUseDefaults, installInstallConfig.dbUseDefaults) &&
        Objects.equals(this.dsFolder, installInstallConfig.dsFolder) &&
        Objects.equals(this.dsName, installInstallConfig.dsName) &&
        Objects.equals(this.dsPort, installInstallConfig.dsPort) &&
        Objects.equals(this.dsS3ApiKey, installInstallConfig.dsS3ApiKey) &&
        Objects.equals(this.dsS3ApiSecret, installInstallConfig.dsS3ApiSecret) &&
        Objects.equals(this.dsS3BucketBinaries, installInstallConfig.dsS3BucketBinaries) &&
        Objects.equals(this.dsS3BucketCells, installInstallConfig.dsS3BucketCells) &&
        Objects.equals(this.dsS3BucketDefault, installInstallConfig.dsS3BucketDefault) &&
        Objects.equals(this.dsS3BucketPersonal, installInstallConfig.dsS3BucketPersonal) &&
        Objects.equals(this.dsS3BucketThumbs, installInstallConfig.dsS3BucketThumbs) &&
        Objects.equals(this.dsS3BucketVersions, installInstallConfig.dsS3BucketVersions) &&
        Objects.equals(this.dsS3Custom, installInstallConfig.dsS3Custom) &&
        Objects.equals(this.dsS3CustomRegion, installInstallConfig.dsS3CustomRegion) &&
        Objects.equals(this.dsType, installInstallConfig.dsType) &&
        Objects.equals(this.frontendApplicationTitle, installInstallConfig.frontendApplicationTitle) &&
        Objects.equals(this.frontendDefaultLanguage, installInstallConfig.frontendDefaultLanguage) &&
        Objects.equals(this.frontendHosts, installInstallConfig.frontendHosts) &&
        Objects.equals(this.frontendLogin, installInstallConfig.frontendLogin) &&
        Objects.equals(this.frontendPassword, installInstallConfig.frontendPassword) &&
        Objects.equals(this.frontendRepeatPassword, installInstallConfig.frontendRepeatPassword) &&
        Objects.equals(this.internalUrl, installInstallConfig.internalUrl) &&
        Objects.equals(this.licenseRequired, installInstallConfig.licenseRequired) &&
        Objects.equals(this.licenseString, installInstallConfig.licenseString);
  }

  @Override
  public int hashCode() {
    return Objects.hash(checkResults, documentsDSN, proxyConfig, useDocumentsDSN, dbConnectionType, dbManualDSN, dbSocketFile, dbSocketName, dbSocketPassword, dbSocketUser, dbTCPHostname, dbTCPName, dbTCPPassword, dbTCPPort, dbTCPUser, dbUseDefaults, dsFolder, dsName, dsPort, dsS3ApiKey, dsS3ApiSecret, dsS3BucketBinaries, dsS3BucketCells, dsS3BucketDefault, dsS3BucketPersonal, dsS3BucketThumbs, dsS3BucketVersions, dsS3Custom, dsS3CustomRegion, dsType, frontendApplicationTitle, frontendDefaultLanguage, frontendHosts, frontendLogin, frontendPassword, frontendRepeatPassword, internalUrl, licenseRequired, licenseString);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InstallInstallConfig {\n");
    sb.append("    checkResults: ").append(toIndentedString(checkResults)).append("\n");
    sb.append("    documentsDSN: ").append(toIndentedString(documentsDSN)).append("\n");
    sb.append("    proxyConfig: ").append(toIndentedString(proxyConfig)).append("\n");
    sb.append("    useDocumentsDSN: ").append(toIndentedString(useDocumentsDSN)).append("\n");
    sb.append("    dbConnectionType: ").append(toIndentedString(dbConnectionType)).append("\n");
    sb.append("    dbManualDSN: ").append(toIndentedString(dbManualDSN)).append("\n");
    sb.append("    dbSocketFile: ").append(toIndentedString(dbSocketFile)).append("\n");
    sb.append("    dbSocketName: ").append(toIndentedString(dbSocketName)).append("\n");
    sb.append("    dbSocketPassword: ").append(toIndentedString(dbSocketPassword)).append("\n");
    sb.append("    dbSocketUser: ").append(toIndentedString(dbSocketUser)).append("\n");
    sb.append("    dbTCPHostname: ").append(toIndentedString(dbTCPHostname)).append("\n");
    sb.append("    dbTCPName: ").append(toIndentedString(dbTCPName)).append("\n");
    sb.append("    dbTCPPassword: ").append(toIndentedString(dbTCPPassword)).append("\n");
    sb.append("    dbTCPPort: ").append(toIndentedString(dbTCPPort)).append("\n");
    sb.append("    dbTCPUser: ").append(toIndentedString(dbTCPUser)).append("\n");
    sb.append("    dbUseDefaults: ").append(toIndentedString(dbUseDefaults)).append("\n");
    sb.append("    dsFolder: ").append(toIndentedString(dsFolder)).append("\n");
    sb.append("    dsName: ").append(toIndentedString(dsName)).append("\n");
    sb.append("    dsPort: ").append(toIndentedString(dsPort)).append("\n");
    sb.append("    dsS3ApiKey: ").append(toIndentedString(dsS3ApiKey)).append("\n");
    sb.append("    dsS3ApiSecret: ").append(toIndentedString(dsS3ApiSecret)).append("\n");
    sb.append("    dsS3BucketBinaries: ").append(toIndentedString(dsS3BucketBinaries)).append("\n");
    sb.append("    dsS3BucketCells: ").append(toIndentedString(dsS3BucketCells)).append("\n");
    sb.append("    dsS3BucketDefault: ").append(toIndentedString(dsS3BucketDefault)).append("\n");
    sb.append("    dsS3BucketPersonal: ").append(toIndentedString(dsS3BucketPersonal)).append("\n");
    sb.append("    dsS3BucketThumbs: ").append(toIndentedString(dsS3BucketThumbs)).append("\n");
    sb.append("    dsS3BucketVersions: ").append(toIndentedString(dsS3BucketVersions)).append("\n");
    sb.append("    dsS3Custom: ").append(toIndentedString(dsS3Custom)).append("\n");
    sb.append("    dsS3CustomRegion: ").append(toIndentedString(dsS3CustomRegion)).append("\n");
    sb.append("    dsType: ").append(toIndentedString(dsType)).append("\n");
    sb.append("    frontendApplicationTitle: ").append(toIndentedString(frontendApplicationTitle)).append("\n");
    sb.append("    frontendDefaultLanguage: ").append(toIndentedString(frontendDefaultLanguage)).append("\n");
    sb.append("    frontendHosts: ").append(toIndentedString(frontendHosts)).append("\n");
    sb.append("    frontendLogin: ").append(toIndentedString(frontendLogin)).append("\n");
    sb.append("    frontendPassword: ").append(toIndentedString(frontendPassword)).append("\n");
    sb.append("    frontendRepeatPassword: ").append(toIndentedString(frontendRepeatPassword)).append("\n");
    sb.append("    internalUrl: ").append(toIndentedString(internalUrl)).append("\n");
    sb.append("    licenseRequired: ").append(toIndentedString(licenseRequired)).append("\n");
    sb.append("    licenseString: ").append(toIndentedString(licenseString)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("CheckResults");
    openapiFields.add("DocumentsDSN");
    openapiFields.add("ProxyConfig");
    openapiFields.add("UseDocumentsDSN");
    openapiFields.add("dbConnectionType");
    openapiFields.add("dbManualDSN");
    openapiFields.add("dbSocketFile");
    openapiFields.add("dbSocketName");
    openapiFields.add("dbSocketPassword");
    openapiFields.add("dbSocketUser");
    openapiFields.add("dbTCPHostname");
    openapiFields.add("dbTCPName");
    openapiFields.add("dbTCPPassword");
    openapiFields.add("dbTCPPort");
    openapiFields.add("dbTCPUser");
    openapiFields.add("dbUseDefaults");
    openapiFields.add("dsFolder");
    openapiFields.add("dsName");
    openapiFields.add("dsPort");
    openapiFields.add("dsS3ApiKey");
    openapiFields.add("dsS3ApiSecret");
    openapiFields.add("dsS3BucketBinaries");
    openapiFields.add("dsS3BucketCells");
    openapiFields.add("dsS3BucketDefault");
    openapiFields.add("dsS3BucketPersonal");
    openapiFields.add("dsS3BucketThumbs");
    openapiFields.add("dsS3BucketVersions");
    openapiFields.add("dsS3Custom");
    openapiFields.add("dsS3CustomRegion");
    openapiFields.add("dsType");
    openapiFields.add("frontendApplicationTitle");
    openapiFields.add("frontendDefaultLanguage");
    openapiFields.add("frontendHosts");
    openapiFields.add("frontendLogin");
    openapiFields.add("frontendPassword");
    openapiFields.add("frontendRepeatPassword");
    openapiFields.add("internalUrl");
    openapiFields.add("licenseRequired");
    openapiFields.add("licenseString");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to InstallInstallConfig
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!InstallInstallConfig.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in InstallInstallConfig is not found in the empty JSON string", InstallInstallConfig.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!InstallInstallConfig.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `InstallInstallConfig` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }
      if (jsonObj.get("CheckResults") != null && !jsonObj.get("CheckResults").isJsonNull()) {
        JsonArray jsonArraycheckResults = jsonObj.getAsJsonArray("CheckResults");
        if (jsonArraycheckResults != null) {
          // ensure the json data is an array
          if (!jsonObj.get("CheckResults").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `CheckResults` to be an array in the JSON string but got `%s`", jsonObj.get("CheckResults").toString()));
          }

          // validate the optional field `CheckResults` (array)
          for (int i = 0; i < jsonArraycheckResults.size(); i++) {
            InstallCheckResult.validateJsonObject(jsonArraycheckResults.get(i).getAsJsonObject());
          };
        }
      }
      if ((jsonObj.get("DocumentsDSN") != null && !jsonObj.get("DocumentsDSN").isJsonNull()) && !jsonObj.get("DocumentsDSN").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `DocumentsDSN` to be a primitive type in the JSON string but got `%s`", jsonObj.get("DocumentsDSN").toString()));
      }
      // validate the optional field `ProxyConfig`
      if (jsonObj.get("ProxyConfig") != null && !jsonObj.get("ProxyConfig").isJsonNull()) {
        InstallProxyConfig.validateJsonObject(jsonObj.getAsJsonObject("ProxyConfig"));
      }
      if ((jsonObj.get("dbConnectionType") != null && !jsonObj.get("dbConnectionType").isJsonNull()) && !jsonObj.get("dbConnectionType").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `dbConnectionType` to be a primitive type in the JSON string but got `%s`", jsonObj.get("dbConnectionType").toString()));
      }
      if ((jsonObj.get("dbManualDSN") != null && !jsonObj.get("dbManualDSN").isJsonNull()) && !jsonObj.get("dbManualDSN").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `dbManualDSN` to be a primitive type in the JSON string but got `%s`", jsonObj.get("dbManualDSN").toString()));
      }
      if ((jsonObj.get("dbSocketFile") != null && !jsonObj.get("dbSocketFile").isJsonNull()) && !jsonObj.get("dbSocketFile").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `dbSocketFile` to be a primitive type in the JSON string but got `%s`", jsonObj.get("dbSocketFile").toString()));
      }
      if ((jsonObj.get("dbSocketName") != null && !jsonObj.get("dbSocketName").isJsonNull()) && !jsonObj.get("dbSocketName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `dbSocketName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("dbSocketName").toString()));
      }
      if ((jsonObj.get("dbSocketPassword") != null && !jsonObj.get("dbSocketPassword").isJsonNull()) && !jsonObj.get("dbSocketPassword").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `dbSocketPassword` to be a primitive type in the JSON string but got `%s`", jsonObj.get("dbSocketPassword").toString()));
      }
      if ((jsonObj.get("dbSocketUser") != null && !jsonObj.get("dbSocketUser").isJsonNull()) && !jsonObj.get("dbSocketUser").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `dbSocketUser` to be a primitive type in the JSON string but got `%s`", jsonObj.get("dbSocketUser").toString()));
      }
      if ((jsonObj.get("dbTCPHostname") != null && !jsonObj.get("dbTCPHostname").isJsonNull()) && !jsonObj.get("dbTCPHostname").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `dbTCPHostname` to be a primitive type in the JSON string but got `%s`", jsonObj.get("dbTCPHostname").toString()));
      }
      if ((jsonObj.get("dbTCPName") != null && !jsonObj.get("dbTCPName").isJsonNull()) && !jsonObj.get("dbTCPName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `dbTCPName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("dbTCPName").toString()));
      }
      if ((jsonObj.get("dbTCPPassword") != null && !jsonObj.get("dbTCPPassword").isJsonNull()) && !jsonObj.get("dbTCPPassword").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `dbTCPPassword` to be a primitive type in the JSON string but got `%s`", jsonObj.get("dbTCPPassword").toString()));
      }
      if ((jsonObj.get("dbTCPPort") != null && !jsonObj.get("dbTCPPort").isJsonNull()) && !jsonObj.get("dbTCPPort").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `dbTCPPort` to be a primitive type in the JSON string but got `%s`", jsonObj.get("dbTCPPort").toString()));
      }
      if ((jsonObj.get("dbTCPUser") != null && !jsonObj.get("dbTCPUser").isJsonNull()) && !jsonObj.get("dbTCPUser").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `dbTCPUser` to be a primitive type in the JSON string but got `%s`", jsonObj.get("dbTCPUser").toString()));
      }
      if ((jsonObj.get("dsFolder") != null && !jsonObj.get("dsFolder").isJsonNull()) && !jsonObj.get("dsFolder").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `dsFolder` to be a primitive type in the JSON string but got `%s`", jsonObj.get("dsFolder").toString()));
      }
      if ((jsonObj.get("dsName") != null && !jsonObj.get("dsName").isJsonNull()) && !jsonObj.get("dsName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `dsName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("dsName").toString()));
      }
      if ((jsonObj.get("dsPort") != null && !jsonObj.get("dsPort").isJsonNull()) && !jsonObj.get("dsPort").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `dsPort` to be a primitive type in the JSON string but got `%s`", jsonObj.get("dsPort").toString()));
      }
      if ((jsonObj.get("dsS3ApiKey") != null && !jsonObj.get("dsS3ApiKey").isJsonNull()) && !jsonObj.get("dsS3ApiKey").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `dsS3ApiKey` to be a primitive type in the JSON string but got `%s`", jsonObj.get("dsS3ApiKey").toString()));
      }
      if ((jsonObj.get("dsS3ApiSecret") != null && !jsonObj.get("dsS3ApiSecret").isJsonNull()) && !jsonObj.get("dsS3ApiSecret").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `dsS3ApiSecret` to be a primitive type in the JSON string but got `%s`", jsonObj.get("dsS3ApiSecret").toString()));
      }
      if ((jsonObj.get("dsS3BucketBinaries") != null && !jsonObj.get("dsS3BucketBinaries").isJsonNull()) && !jsonObj.get("dsS3BucketBinaries").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `dsS3BucketBinaries` to be a primitive type in the JSON string but got `%s`", jsonObj.get("dsS3BucketBinaries").toString()));
      }
      if ((jsonObj.get("dsS3BucketCells") != null && !jsonObj.get("dsS3BucketCells").isJsonNull()) && !jsonObj.get("dsS3BucketCells").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `dsS3BucketCells` to be a primitive type in the JSON string but got `%s`", jsonObj.get("dsS3BucketCells").toString()));
      }
      if ((jsonObj.get("dsS3BucketDefault") != null && !jsonObj.get("dsS3BucketDefault").isJsonNull()) && !jsonObj.get("dsS3BucketDefault").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `dsS3BucketDefault` to be a primitive type in the JSON string but got `%s`", jsonObj.get("dsS3BucketDefault").toString()));
      }
      if ((jsonObj.get("dsS3BucketPersonal") != null && !jsonObj.get("dsS3BucketPersonal").isJsonNull()) && !jsonObj.get("dsS3BucketPersonal").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `dsS3BucketPersonal` to be a primitive type in the JSON string but got `%s`", jsonObj.get("dsS3BucketPersonal").toString()));
      }
      if ((jsonObj.get("dsS3BucketThumbs") != null && !jsonObj.get("dsS3BucketThumbs").isJsonNull()) && !jsonObj.get("dsS3BucketThumbs").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `dsS3BucketThumbs` to be a primitive type in the JSON string but got `%s`", jsonObj.get("dsS3BucketThumbs").toString()));
      }
      if ((jsonObj.get("dsS3BucketVersions") != null && !jsonObj.get("dsS3BucketVersions").isJsonNull()) && !jsonObj.get("dsS3BucketVersions").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `dsS3BucketVersions` to be a primitive type in the JSON string but got `%s`", jsonObj.get("dsS3BucketVersions").toString()));
      }
      if ((jsonObj.get("dsS3Custom") != null && !jsonObj.get("dsS3Custom").isJsonNull()) && !jsonObj.get("dsS3Custom").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `dsS3Custom` to be a primitive type in the JSON string but got `%s`", jsonObj.get("dsS3Custom").toString()));
      }
      if ((jsonObj.get("dsS3CustomRegion") != null && !jsonObj.get("dsS3CustomRegion").isJsonNull()) && !jsonObj.get("dsS3CustomRegion").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `dsS3CustomRegion` to be a primitive type in the JSON string but got `%s`", jsonObj.get("dsS3CustomRegion").toString()));
      }
      if ((jsonObj.get("dsType") != null && !jsonObj.get("dsType").isJsonNull()) && !jsonObj.get("dsType").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `dsType` to be a primitive type in the JSON string but got `%s`", jsonObj.get("dsType").toString()));
      }
      if ((jsonObj.get("frontendApplicationTitle") != null && !jsonObj.get("frontendApplicationTitle").isJsonNull()) && !jsonObj.get("frontendApplicationTitle").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `frontendApplicationTitle` to be a primitive type in the JSON string but got `%s`", jsonObj.get("frontendApplicationTitle").toString()));
      }
      if ((jsonObj.get("frontendDefaultLanguage") != null && !jsonObj.get("frontendDefaultLanguage").isJsonNull()) && !jsonObj.get("frontendDefaultLanguage").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `frontendDefaultLanguage` to be a primitive type in the JSON string but got `%s`", jsonObj.get("frontendDefaultLanguage").toString()));
      }
      if ((jsonObj.get("frontendHosts") != null && !jsonObj.get("frontendHosts").isJsonNull()) && !jsonObj.get("frontendHosts").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `frontendHosts` to be a primitive type in the JSON string but got `%s`", jsonObj.get("frontendHosts").toString()));
      }
      if ((jsonObj.get("frontendLogin") != null && !jsonObj.get("frontendLogin").isJsonNull()) && !jsonObj.get("frontendLogin").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `frontendLogin` to be a primitive type in the JSON string but got `%s`", jsonObj.get("frontendLogin").toString()));
      }
      if ((jsonObj.get("frontendPassword") != null && !jsonObj.get("frontendPassword").isJsonNull()) && !jsonObj.get("frontendPassword").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `frontendPassword` to be a primitive type in the JSON string but got `%s`", jsonObj.get("frontendPassword").toString()));
      }
      if ((jsonObj.get("frontendRepeatPassword") != null && !jsonObj.get("frontendRepeatPassword").isJsonNull()) && !jsonObj.get("frontendRepeatPassword").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `frontendRepeatPassword` to be a primitive type in the JSON string but got `%s`", jsonObj.get("frontendRepeatPassword").toString()));
      }
      if ((jsonObj.get("internalUrl") != null && !jsonObj.get("internalUrl").isJsonNull()) && !jsonObj.get("internalUrl").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `internalUrl` to be a primitive type in the JSON string but got `%s`", jsonObj.get("internalUrl").toString()));
      }
      if ((jsonObj.get("licenseString") != null && !jsonObj.get("licenseString").isJsonNull()) && !jsonObj.get("licenseString").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `licenseString` to be a primitive type in the JSON string but got `%s`", jsonObj.get("licenseString").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!InstallInstallConfig.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'InstallInstallConfig' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<InstallInstallConfig> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(InstallInstallConfig.class));

       return (TypeAdapter<T>) new TypeAdapter<InstallInstallConfig>() {
           @Override
           public void write(JsonWriter out, InstallInstallConfig value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public InstallInstallConfig read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of InstallInstallConfig given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of InstallInstallConfig
  * @throws IOException if the JSON string is invalid with respect to InstallInstallConfig
  */
  public static InstallInstallConfig fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, InstallInstallConfig.class);
  }

 /**
  * Convert an instance of InstallInstallConfig to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

