/*
 * Pydio Cells Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.pydio.cells.openapi.model;

import com.google.gson.JsonElement;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

import java.io.IOException;

/**
 * Gets or Sets registryActionType
 */
@JsonAdapter(RegistryActionType.Adapter.class)
public enum RegistryActionType {

    ANY("ANY"),

    FULL_DIFF("FULL_DIFF"),

    FULL_LIST("FULL_LIST"),

    CREATE("CREATE"),

    UPDATE("UPDATE"),

    DELETE("DELETE");

    private final String value;

    RegistryActionType(String value) {
        this.value = value;
    }

    public String getValue() {
        return value;
    }

    @Override
    public String toString() {
        return String.valueOf(value);
    }

    public static RegistryActionType fromValue(String value) {
        for (RegistryActionType b : RegistryActionType.values()) {
            if (b.value.equals(value)) {
                return b;
            }
        }
        throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<RegistryActionType> {
        @Override
        public void write(final JsonWriter jsonWriter, final RegistryActionType enumeration) throws IOException {
            jsonWriter.value(enumeration.getValue());
        }

        @Override
        public RegistryActionType read(final JsonReader jsonReader) throws IOException {
            String value = jsonReader.nextString();
            return RegistryActionType.fromValue(value);
        }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
        String value = jsonElement.getAsString();
        RegistryActionType.fromValue(value);
    }
}

