/*
 * Pydio Cells Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.pydio.cells.openapi.model;

import com.google.gson.Gson;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.pydio.cells.openapi.JSON;

import java.io.IOException;
import java.util.HashSet;
import java.util.Map;
import java.util.Objects;
import java.util.Set;

/**
 * RestUserJobRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-03-16T11:01:01.368056162+01:00[Europe/Berlin]", comments = "Generator version: 7.4.0")
public class RestUserJobRequest {
  public static final String SERIALIZED_NAME_JOB_NAME = "JobName";
  @SerializedName(SERIALIZED_NAME_JOB_NAME)
  private String jobName;

  public static final String SERIALIZED_NAME_JSON_PARAMETERS = "JsonParameters";
  @SerializedName(SERIALIZED_NAME_JSON_PARAMETERS)
  private String jsonParameters;

  public RestUserJobRequest() {
  }

  public RestUserJobRequest jobName(String jobName) {
    this.jobName = jobName;
    return this;
  }

   /**
   * Get jobName
   * @return jobName
  **/
  @javax.annotation.Nullable
  public String getJobName() {
    return jobName;
  }

  public void setJobName(String jobName) {
    this.jobName = jobName;
  }


  public RestUserJobRequest jsonParameters(String jsonParameters) {
    this.jsonParameters = jsonParameters;
    return this;
  }

   /**
   * Get jsonParameters
   * @return jsonParameters
  **/
  @javax.annotation.Nullable
  public String getJsonParameters() {
    return jsonParameters;
  }

  public void setJsonParameters(String jsonParameters) {
    this.jsonParameters = jsonParameters;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RestUserJobRequest restUserJobRequest = (RestUserJobRequest) o;
    return Objects.equals(this.jobName, restUserJobRequest.jobName) &&
        Objects.equals(this.jsonParameters, restUserJobRequest.jsonParameters);
  }

  @Override
  public int hashCode() {
    return Objects.hash(jobName, jsonParameters);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RestUserJobRequest {\n");
    sb.append("    jobName: ").append(toIndentedString(jobName)).append("\n");
    sb.append("    jsonParameters: ").append(toIndentedString(jsonParameters)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("JobName");
    openapiFields.add("JsonParameters");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to RestUserJobRequest
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!RestUserJobRequest.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in RestUserJobRequest is not found in the empty JSON string", RestUserJobRequest.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!RestUserJobRequest.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `RestUserJobRequest` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("JobName") != null && !jsonObj.get("JobName").isJsonNull()) && !jsonObj.get("JobName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `JobName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("JobName").toString()));
      }
      if ((jsonObj.get("JsonParameters") != null && !jsonObj.get("JsonParameters").isJsonNull()) && !jsonObj.get("JsonParameters").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `JsonParameters` to be a primitive type in the JSON string but got `%s`", jsonObj.get("JsonParameters").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!RestUserJobRequest.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'RestUserJobRequest' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<RestUserJobRequest> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(RestUserJobRequest.class));

       return (TypeAdapter<T>) new TypeAdapter<RestUserJobRequest>() {
           @Override
           public void write(JsonWriter out, RestUserJobRequest value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public RestUserJobRequest read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of RestUserJobRequest given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of RestUserJobRequest
  * @throws IOException if the JSON string is invalid with respect to RestUserJobRequest
  */
  public static RestUserJobRequest fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, RestUserJobRequest.class);
  }

 /**
  * Convert an instance of RestUserJobRequest to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

