/*
 * Pydio Cells Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.pydio.cells.openapi.model;

import java.util.Objects;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.pydio.cells.openapi.model.ActivitySubscription;

import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.pydio.cells.openapi.JSON;

/**
 * RestSubscriptionsCollection
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-02-19T16:47:50.322929+01:00[Europe/Berlin]", comments = "Generator version: 7.11.0")
public class RestSubscriptionsCollection {
    public static final String SERIALIZED_NAME_SUBSCRIPTIONS = "subscriptions";
    @SerializedName(SERIALIZED_NAME_SUBSCRIPTIONS)
    @javax.annotation.Nullable
    private List<ActivitySubscription> subscriptions = new ArrayList<>();

    public RestSubscriptionsCollection() {
    }

    public RestSubscriptionsCollection subscriptions(@javax.annotation.Nullable List<ActivitySubscription> subscriptions) {
        this.subscriptions = subscriptions;
        return this;
    }

    public RestSubscriptionsCollection addSubscriptionsItem(ActivitySubscription subscriptionsItem) {
        if (this.subscriptions == null) {
            this.subscriptions = new ArrayList<>();
        }
        this.subscriptions.add(subscriptionsItem);
        return this;
    }

    /**
     * Get subscriptions
     *
     * @return subscriptions
     */
    @javax.annotation.Nullable
    public List<ActivitySubscription> getSubscriptions() {
        return subscriptions;
    }

    public void setSubscriptions(@javax.annotation.Nullable List<ActivitySubscription> subscriptions) {
        this.subscriptions = subscriptions;
    }


    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        RestSubscriptionsCollection restSubscriptionsCollection = (RestSubscriptionsCollection) o;
        return Objects.equals(this.subscriptions, restSubscriptionsCollection.subscriptions);
    }

    @Override
    public int hashCode() {
        return Objects.hash(subscriptions);
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class RestSubscriptionsCollection {\n");
        sb.append("    subscriptions: ").append(toIndentedString(subscriptions)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }


    public static HashSet<String> openapiFields;
    public static HashSet<String> openapiRequiredFields;

    static {
        // a set of all properties/fields (JSON key names)
        openapiFields = new HashSet<String>();
        openapiFields.add("subscriptions");

        // a set of required properties/fields (JSON key names)
        openapiRequiredFields = new HashSet<String>();
    }

    /**
     * Validates the JSON Element and throws an exception if issues found
     *
     * @param jsonElement JSON Element
     * @throws IOException if the JSON Element is invalid with respect to RestSubscriptionsCollection
     */
    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
        if (jsonElement == null) {
            if (!RestSubscriptionsCollection.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
                throw new IllegalArgumentException(String.format("The required field(s) %s in RestSubscriptionsCollection is not found in the empty JSON string", RestSubscriptionsCollection.openapiRequiredFields.toString()));
            }
        }

        Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
        // check to see if the JSON string contains additional fields
        for (Map.Entry<String, JsonElement> entry : entries) {
            if (!RestSubscriptionsCollection.openapiFields.contains(entry.getKey())) {
                throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `RestSubscriptionsCollection` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
            }
        }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
        if (jsonObj.get("subscriptions") != null && !jsonObj.get("subscriptions").isJsonNull()) {
            JsonArray jsonArraysubscriptions = jsonObj.getAsJsonArray("subscriptions");
            if (jsonArraysubscriptions != null) {
                // ensure the json data is an array
                if (!jsonObj.get("subscriptions").isJsonArray()) {
                    throw new IllegalArgumentException(String.format("Expected the field `subscriptions` to be an array in the JSON string but got `%s`", jsonObj.get("subscriptions").toString()));
                }

                // validate the optional field `subscriptions` (array)
                for (int i = 0; i < jsonArraysubscriptions.size(); i++) {
                    ActivitySubscription.validateJsonElement(jsonArraysubscriptions.get(i));
                }
                ;
            }
        }
    }

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!RestSubscriptionsCollection.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes 'RestSubscriptionsCollection' and its subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<RestSubscriptionsCollection> thisAdapter
                    = gson.getDelegateAdapter(this, TypeToken.get(RestSubscriptionsCollection.class));

            return (TypeAdapter<T>) new TypeAdapter<RestSubscriptionsCollection>() {
                @Override
                public void write(JsonWriter out, RestSubscriptionsCollection value) throws IOException {
                    JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
                    elementAdapter.write(out, obj);
                }

                @Override
                public RestSubscriptionsCollection read(JsonReader in) throws IOException {
                    JsonElement jsonElement = elementAdapter.read(in);
                    validateJsonElement(jsonElement);
                    return thisAdapter.fromJsonTree(jsonElement);
                }

            }.nullSafe();
        }
    }

    /**
     * Create an instance of RestSubscriptionsCollection given an JSON string
     *
     * @param jsonString JSON string
     * @return An instance of RestSubscriptionsCollection
     * @throws IOException if the JSON string is invalid with respect to RestSubscriptionsCollection
     */
    public static RestSubscriptionsCollection fromJson(String jsonString) throws IOException {
        return JSON.getGson().fromJson(jsonString, RestSubscriptionsCollection.class);
    }

    /**
     * Convert an instance of RestSubscriptionsCollection to an JSON string
     *
     * @return JSON string
     */
    public String toJson() {
        return JSON.getGson().toJson(this);
    }
}

