/*
 * Pydio Cells Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.pydio.cells.openapi.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.pydio.cells.openapi.model.TreeNode;
import com.pydio.cells.openapi.model.TreeSearchFacet;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * RestSearchResults
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-05-05T12:35:48.905699+02:00[Europe/Berlin]")
public class RestSearchResults {
  public static final String SERIALIZED_NAME_FACETS = "Facets";
  @SerializedName(SERIALIZED_NAME_FACETS)
  private List<TreeSearchFacet> facets = null;

  public static final String SERIALIZED_NAME_RESULTS = "Results";
  @SerializedName(SERIALIZED_NAME_RESULTS)
  private List<TreeNode> results = null;

  public static final String SERIALIZED_NAME_TOTAL = "Total";
  @SerializedName(SERIALIZED_NAME_TOTAL)
  private Integer total;

  public RestSearchResults() { 
  }

  public RestSearchResults facets(List<TreeSearchFacet> facets) {
    
    this.facets = facets;
    return this;
  }

  public RestSearchResults addFacetsItem(TreeSearchFacet facetsItem) {
    if (this.facets == null) {
      this.facets = new ArrayList<TreeSearchFacet>();
    }
    this.facets.add(facetsItem);
    return this;
  }

   /**
   * Get facets
   * @return facets
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<TreeSearchFacet> getFacets() {
    return facets;
  }


  public void setFacets(List<TreeSearchFacet> facets) {
    this.facets = facets;
  }


  public RestSearchResults results(List<TreeNode> results) {
    
    this.results = results;
    return this;
  }

  public RestSearchResults addResultsItem(TreeNode resultsItem) {
    if (this.results == null) {
      this.results = new ArrayList<TreeNode>();
    }
    this.results.add(resultsItem);
    return this;
  }

   /**
   * Get results
   * @return results
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<TreeNode> getResults() {
    return results;
  }


  public void setResults(List<TreeNode> results) {
    this.results = results;
  }


  public RestSearchResults total(Integer total) {
    
    this.total = total;
    return this;
  }

   /**
   * Get total
   * @return total
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getTotal() {
    return total;
  }


  public void setTotal(Integer total) {
    this.total = total;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RestSearchResults restSearchResults = (RestSearchResults) o;
    return Objects.equals(this.facets, restSearchResults.facets) &&
        Objects.equals(this.results, restSearchResults.results) &&
        Objects.equals(this.total, restSearchResults.total);
  }

  @Override
  public int hashCode() {
    return Objects.hash(facets, results, total);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RestSearchResults {\n");
    sb.append("    facets: ").append(toIndentedString(facets)).append("\n");
    sb.append("    results: ").append(toIndentedString(results)).append("\n");
    sb.append("    total: ").append(toIndentedString(total)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

