/*
 * Pydio Cells Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.pydio.cells.openapi.model;

import com.google.gson.Gson;
import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.pydio.cells.openapi.JSON;

import java.io.IOException;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Set;

/**
 * RestWorkspaceCollection
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-03-16T11:01:01.368056162+01:00[Europe/Berlin]", comments = "Generator version: 7.4.0")
public class RestWorkspaceCollection {
  public static final String SERIALIZED_NAME_TOTAL = "Total";
  @SerializedName(SERIALIZED_NAME_TOTAL)
  private Integer total;

  public static final String SERIALIZED_NAME_WORKSPACES = "Workspaces";
  @SerializedName(SERIALIZED_NAME_WORKSPACES)
  private List<IdmWorkspace> workspaces;

  public RestWorkspaceCollection() {
  }

  public RestWorkspaceCollection total(Integer total) {
    this.total = total;
    return this;
  }

   /**
   * Get total
   * @return total
  **/
  @javax.annotation.Nullable
  public Integer getTotal() {
    return total;
  }

  public void setTotal(Integer total) {
    this.total = total;
  }


  public RestWorkspaceCollection workspaces(List<IdmWorkspace> workspaces) {
    this.workspaces = workspaces;
    return this;
  }

  public RestWorkspaceCollection addWorkspacesItem(IdmWorkspace workspacesItem) {
    if (this.workspaces == null) {
      this.workspaces = new ArrayList<>();
    }
    this.workspaces.add(workspacesItem);
    return this;
  }

   /**
   * Get workspaces
   * @return workspaces
  **/
  @javax.annotation.Nullable
  public List<IdmWorkspace> getWorkspaces() {
    return workspaces;
  }

  public void setWorkspaces(List<IdmWorkspace> workspaces) {
    this.workspaces = workspaces;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RestWorkspaceCollection restWorkspaceCollection = (RestWorkspaceCollection) o;
    return Objects.equals(this.total, restWorkspaceCollection.total) &&
        Objects.equals(this.workspaces, restWorkspaceCollection.workspaces);
  }

  @Override
  public int hashCode() {
    return Objects.hash(total, workspaces);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RestWorkspaceCollection {\n");
    sb.append("    total: ").append(toIndentedString(total)).append("\n");
    sb.append("    workspaces: ").append(toIndentedString(workspaces)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("Total");
    openapiFields.add("Workspaces");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to RestWorkspaceCollection
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!RestWorkspaceCollection.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in RestWorkspaceCollection is not found in the empty JSON string", RestWorkspaceCollection.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!RestWorkspaceCollection.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `RestWorkspaceCollection` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (jsonObj.get("Workspaces") != null && !jsonObj.get("Workspaces").isJsonNull()) {
        JsonArray jsonArrayworkspaces = jsonObj.getAsJsonArray("Workspaces");
        if (jsonArrayworkspaces != null) {
          // ensure the json data is an array
          if (!jsonObj.get("Workspaces").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `Workspaces` to be an array in the JSON string but got `%s`", jsonObj.get("Workspaces").toString()));
          }

          // validate the optional field `Workspaces` (array)
          for (int i = 0; i < jsonArrayworkspaces.size(); i++) {
            IdmWorkspace.validateJsonElement(jsonArrayworkspaces.get(i));
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!RestWorkspaceCollection.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'RestWorkspaceCollection' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<RestWorkspaceCollection> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(RestWorkspaceCollection.class));

       return (TypeAdapter<T>) new TypeAdapter<RestWorkspaceCollection>() {
           @Override
           public void write(JsonWriter out, RestWorkspaceCollection value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public RestWorkspaceCollection read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of RestWorkspaceCollection given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of RestWorkspaceCollection
  * @throws IOException if the JSON string is invalid with respect to RestWorkspaceCollection
  */
  public static RestWorkspaceCollection fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, RestWorkspaceCollection.class);
  }

 /**
  * Convert an instance of RestWorkspaceCollection to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

