/*
 * Pydio Cells Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.pydio.cells.openapi.model;

import com.google.gson.Gson;
import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.pydio.cells.openapi.JSON;

import java.io.IOException;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Map.Entry;
import java.util.Objects;
import java.util.Set;

import io.swagger.annotations.ApiModelProperty;

/**
 * RestSettingsSection
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-01-20T11:40:14.306426+01:00[Europe/Berlin]")
public class RestSettingsSection {
  public static final String SERIALIZED_NAME_C_H_I_L_D_R_E_N = "CHILDREN";
  @SerializedName(SERIALIZED_NAME_C_H_I_L_D_R_E_N)
  private List<RestSettingsEntry> CHILDREN = null;

  public static final String SERIALIZED_NAME_D_E_S_C_R_I_P_T_I_O_N = "DESCRIPTION";
  @SerializedName(SERIALIZED_NAME_D_E_S_C_R_I_P_T_I_O_N)
  private String DESCRIPTION;

  public static final String SERIALIZED_NAME_KEY = "Key";
  @SerializedName(SERIALIZED_NAME_KEY)
  private String key;

  public static final String SERIALIZED_NAME_L_A_B_E_L = "LABEL";
  @SerializedName(SERIALIZED_NAME_L_A_B_E_L)
  private String LABEL;

  public RestSettingsSection() {
  }

  public RestSettingsSection CHILDREN(List<RestSettingsEntry> CHILDREN) {
    
    this.CHILDREN = CHILDREN;
    return this;
  }

  public RestSettingsSection addCHILDRENItem(RestSettingsEntry CHILDRENItem) {
    if (this.CHILDREN == null) {
      this.CHILDREN = new ArrayList<>();
    }
    this.CHILDREN.add(CHILDRENItem);
    return this;
  }

   /**
   * Get CHILDREN
   * @return CHILDREN
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<RestSettingsEntry> getCHILDREN() {
    return CHILDREN;
  }


  public void setCHILDREN(List<RestSettingsEntry> CHILDREN) {
    this.CHILDREN = CHILDREN;
  }


  public RestSettingsSection DESCRIPTION(String DESCRIPTION) {
    
    this.DESCRIPTION = DESCRIPTION;
    return this;
  }

   /**
   * Get DESCRIPTION
   * @return DESCRIPTION
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getDESCRIPTION() {
    return DESCRIPTION;
  }


  public void setDESCRIPTION(String DESCRIPTION) {
    this.DESCRIPTION = DESCRIPTION;
  }


  public RestSettingsSection key(String key) {
    
    this.key = key;
    return this;
  }

   /**
   * Get key
   * @return key
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getKey() {
    return key;
  }


  public void setKey(String key) {
    this.key = key;
  }


  public RestSettingsSection LABEL(String LABEL) {
    
    this.LABEL = LABEL;
    return this;
  }

   /**
   * Get LABEL
   * @return LABEL
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getLABEL() {
    return LABEL;
  }


  public void setLABEL(String LABEL) {
    this.LABEL = LABEL;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RestSettingsSection restSettingsSection = (RestSettingsSection) o;
    return Objects.equals(this.CHILDREN, restSettingsSection.CHILDREN) &&
        Objects.equals(this.DESCRIPTION, restSettingsSection.DESCRIPTION) &&
        Objects.equals(this.key, restSettingsSection.key) &&
        Objects.equals(this.LABEL, restSettingsSection.LABEL);
  }

  @Override
  public int hashCode() {
    return Objects.hash(CHILDREN, DESCRIPTION, key, LABEL);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RestSettingsSection {\n");
    sb.append("    CHILDREN: ").append(toIndentedString(CHILDREN)).append("\n");
    sb.append("    DESCRIPTION: ").append(toIndentedString(DESCRIPTION)).append("\n");
    sb.append("    key: ").append(toIndentedString(key)).append("\n");
    sb.append("    LABEL: ").append(toIndentedString(LABEL)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("CHILDREN");
    openapiFields.add("DESCRIPTION");
    openapiFields.add("Key");
    openapiFields.add("LABEL");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to RestSettingsSection
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!RestSettingsSection.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in RestSettingsSection is not found in the empty JSON string", RestSettingsSection.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!RestSettingsSection.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `RestSettingsSection` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }
      if (jsonObj.get("CHILDREN") != null && !jsonObj.get("CHILDREN").isJsonNull()) {
        JsonArray jsonArrayCHILDREN = jsonObj.getAsJsonArray("CHILDREN");
        if (jsonArrayCHILDREN != null) {
          // ensure the json data is an array
          if (!jsonObj.get("CHILDREN").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `CHILDREN` to be an array in the JSON string but got `%s`", jsonObj.get("CHILDREN").toString()));
          }

          // validate the optional field `CHILDREN` (array)
          for (int i = 0; i < jsonArrayCHILDREN.size(); i++) {
            RestSettingsEntry.validateJsonObject(jsonArrayCHILDREN.get(i).getAsJsonObject());
          };
        }
      }
      if ((jsonObj.get("DESCRIPTION") != null && !jsonObj.get("DESCRIPTION").isJsonNull()) && !jsonObj.get("DESCRIPTION").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `DESCRIPTION` to be a primitive type in the JSON string but got `%s`", jsonObj.get("DESCRIPTION").toString()));
      }
      if ((jsonObj.get("Key") != null && !jsonObj.get("Key").isJsonNull()) && !jsonObj.get("Key").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `Key` to be a primitive type in the JSON string but got `%s`", jsonObj.get("Key").toString()));
      }
      if ((jsonObj.get("LABEL") != null && !jsonObj.get("LABEL").isJsonNull()) && !jsonObj.get("LABEL").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `LABEL` to be a primitive type in the JSON string but got `%s`", jsonObj.get("LABEL").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!RestSettingsSection.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'RestSettingsSection' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<RestSettingsSection> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(RestSettingsSection.class));

       return (TypeAdapter<T>) new TypeAdapter<RestSettingsSection>() {
           @Override
           public void write(JsonWriter out, RestSettingsSection value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public RestSettingsSection read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of RestSettingsSection given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of RestSettingsSection
  * @throws IOException if the JSON string is invalid with respect to RestSettingsSection
  */
  public static RestSettingsSection fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, RestSettingsSection.class);
  }

 /**
  * Convert an instance of RestSettingsSection to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

