/*
 * Pydio Cells Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.pydio.cells.openapi.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.pydio.cells.openapi.model.RestSettingsAccess;
import com.pydio.cells.openapi.model.RestSettingsEntryMeta;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * RestSettingsEntry
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-02-19T22:47:44.466567+01:00[Europe/Berlin]")
public class RestSettingsEntry {
  public static final String SERIALIZED_NAME_KEY = "Key";
  @SerializedName(SERIALIZED_NAME_KEY)
  private String key;

  public static final String SERIALIZED_NAME_LABEL = "Label";
  @SerializedName(SERIALIZED_NAME_LABEL)
  private String label;

  public static final String SERIALIZED_NAME_DESCRIPTION = "Description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  private String description;

  public static final String SERIALIZED_NAME_MANAGER = "Manager";
  @SerializedName(SERIALIZED_NAME_MANAGER)
  private String manager;

  public static final String SERIALIZED_NAME_ALIAS = "Alias";
  @SerializedName(SERIALIZED_NAME_ALIAS)
  private String alias;

  public static final String SERIALIZED_NAME_METADATA = "Metadata";
  @SerializedName(SERIALIZED_NAME_METADATA)
  private RestSettingsEntryMeta metadata;

  public static final String SERIALIZED_NAME_ACCESSES = "Accesses";
  @SerializedName(SERIALIZED_NAME_ACCESSES)
  private Map<String, RestSettingsAccess> accesses = null;

  public static final String SERIALIZED_NAME_FEATURE = "Feature";
  @SerializedName(SERIALIZED_NAME_FEATURE)
  private String feature;

  public RestSettingsEntry() { 
  }

  public RestSettingsEntry key(String key) {
    
    this.key = key;
    return this;
  }

   /**
   * Get key
   * @return key
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getKey() {
    return key;
  }


  public void setKey(String key) {
    this.key = key;
  }


  public RestSettingsEntry label(String label) {
    
    this.label = label;
    return this;
  }

   /**
   * Get label
   * @return label
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getLabel() {
    return label;
  }


  public void setLabel(String label) {
    this.label = label;
  }


  public RestSettingsEntry description(String description) {
    
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getDescription() {
    return description;
  }


  public void setDescription(String description) {
    this.description = description;
  }


  public RestSettingsEntry manager(String manager) {
    
    this.manager = manager;
    return this;
  }

   /**
   * Get manager
   * @return manager
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getManager() {
    return manager;
  }


  public void setManager(String manager) {
    this.manager = manager;
  }


  public RestSettingsEntry alias(String alias) {
    
    this.alias = alias;
    return this;
  }

   /**
   * Get alias
   * @return alias
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getAlias() {
    return alias;
  }


  public void setAlias(String alias) {
    this.alias = alias;
  }


  public RestSettingsEntry metadata(RestSettingsEntryMeta metadata) {
    
    this.metadata = metadata;
    return this;
  }

   /**
   * Get metadata
   * @return metadata
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public RestSettingsEntryMeta getMetadata() {
    return metadata;
  }


  public void setMetadata(RestSettingsEntryMeta metadata) {
    this.metadata = metadata;
  }


  public RestSettingsEntry accesses(Map<String, RestSettingsAccess> accesses) {
    
    this.accesses = accesses;
    return this;
  }

  public RestSettingsEntry putAccessesItem(String key, RestSettingsAccess accessesItem) {
    if (this.accesses == null) {
      this.accesses = new HashMap<String, RestSettingsAccess>();
    }
    this.accesses.put(key, accessesItem);
    return this;
  }

   /**
   * Get accesses
   * @return accesses
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Map<String, RestSettingsAccess> getAccesses() {
    return accesses;
  }


  public void setAccesses(Map<String, RestSettingsAccess> accesses) {
    this.accesses = accesses;
  }


  public RestSettingsEntry feature(String feature) {
    
    this.feature = feature;
    return this;
  }

   /**
   * Get feature
   * @return feature
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getFeature() {
    return feature;
  }


  public void setFeature(String feature) {
    this.feature = feature;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RestSettingsEntry restSettingsEntry = (RestSettingsEntry) o;
    return Objects.equals(this.key, restSettingsEntry.key) &&
        Objects.equals(this.label, restSettingsEntry.label) &&
        Objects.equals(this.description, restSettingsEntry.description) &&
        Objects.equals(this.manager, restSettingsEntry.manager) &&
        Objects.equals(this.alias, restSettingsEntry.alias) &&
        Objects.equals(this.metadata, restSettingsEntry.metadata) &&
        Objects.equals(this.accesses, restSettingsEntry.accesses) &&
        Objects.equals(this.feature, restSettingsEntry.feature);
  }

  @Override
  public int hashCode() {
    return Objects.hash(key, label, description, manager, alias, metadata, accesses, feature);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RestSettingsEntry {\n");
    sb.append("    key: ").append(toIndentedString(key)).append("\n");
    sb.append("    label: ").append(toIndentedString(label)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    manager: ").append(toIndentedString(manager)).append("\n");
    sb.append("    alias: ").append(toIndentedString(alias)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("    accesses: ").append(toIndentedString(accesses)).append("\n");
    sb.append("    feature: ").append(toIndentedString(feature)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

