/*
 * Pydio Cells Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.pydio.cells.openapi.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.pydio.cells.openapi.model.UpdatePackage;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * UpdateUpdateResponse
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-02-19T22:47:44.466567+01:00[Europe/Berlin]")
public class UpdateUpdateResponse {
  public static final String SERIALIZED_NAME_CHANNEL = "Channel";
  @SerializedName(SERIALIZED_NAME_CHANNEL)
  private String channel;

  public static final String SERIALIZED_NAME_AVAILABLE_BINARIES = "AvailableBinaries";
  @SerializedName(SERIALIZED_NAME_AVAILABLE_BINARIES)
  private List<UpdatePackage> availableBinaries = null;

  public UpdateUpdateResponse() { 
  }

  public UpdateUpdateResponse channel(String channel) {
    
    this.channel = channel;
    return this;
  }

   /**
   * Get channel
   * @return channel
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getChannel() {
    return channel;
  }


  public void setChannel(String channel) {
    this.channel = channel;
  }


  public UpdateUpdateResponse availableBinaries(List<UpdatePackage> availableBinaries) {
    
    this.availableBinaries = availableBinaries;
    return this;
  }

  public UpdateUpdateResponse addAvailableBinariesItem(UpdatePackage availableBinariesItem) {
    if (this.availableBinaries == null) {
      this.availableBinaries = new ArrayList<UpdatePackage>();
    }
    this.availableBinaries.add(availableBinariesItem);
    return this;
  }

   /**
   * Get availableBinaries
   * @return availableBinaries
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<UpdatePackage> getAvailableBinaries() {
    return availableBinaries;
  }


  public void setAvailableBinaries(List<UpdatePackage> availableBinaries) {
    this.availableBinaries = availableBinaries;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdateUpdateResponse updateUpdateResponse = (UpdateUpdateResponse) o;
    return Objects.equals(this.channel, updateUpdateResponse.channel) &&
        Objects.equals(this.availableBinaries, updateUpdateResponse.availableBinaries);
  }

  @Override
  public int hashCode() {
    return Objects.hash(channel, availableBinaries);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdateUpdateResponse {\n");
    sb.append("    channel: ").append(toIndentedString(channel)).append("\n");
    sb.append("    availableBinaries: ").append(toIndentedString(availableBinaries)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

