/*
 * Pydio Cells Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.pydio.cells.openapi.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * UpdateApplyUpdateRequest
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-02-19T22:47:44.466567+01:00[Europe/Berlin]")
public class UpdateApplyUpdateRequest {
  public static final String SERIALIZED_NAME_TARGET_VERSION = "TargetVersion";
  @SerializedName(SERIALIZED_NAME_TARGET_VERSION)
  private String targetVersion;

  public static final String SERIALIZED_NAME_PACKAGE_NAME = "PackageName";
  @SerializedName(SERIALIZED_NAME_PACKAGE_NAME)
  private String packageName;

  public UpdateApplyUpdateRequest() { 
  }

  public UpdateApplyUpdateRequest targetVersion(String targetVersion) {
    
    this.targetVersion = targetVersion;
    return this;
  }

   /**
   * Get targetVersion
   * @return targetVersion
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getTargetVersion() {
    return targetVersion;
  }


  public void setTargetVersion(String targetVersion) {
    this.targetVersion = targetVersion;
  }


  public UpdateApplyUpdateRequest packageName(String packageName) {
    
    this.packageName = packageName;
    return this;
  }

   /**
   * Get packageName
   * @return packageName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getPackageName() {
    return packageName;
  }


  public void setPackageName(String packageName) {
    this.packageName = packageName;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdateApplyUpdateRequest updateApplyUpdateRequest = (UpdateApplyUpdateRequest) o;
    return Objects.equals(this.targetVersion, updateApplyUpdateRequest.targetVersion) &&
        Objects.equals(this.packageName, updateApplyUpdateRequest.packageName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(targetVersion, packageName);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdateApplyUpdateRequest {\n");
    sb.append("    targetVersion: ").append(toIndentedString(targetVersion)).append("\n");
    sb.append("    packageName: ").append(toIndentedString(packageName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

