/*
 * Pydio Cells Rest API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.pydio.cells.openapi.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.pydio.cells.openapi.model.PackagePackageStatus;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * UpdatePackage
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-05-09T15:35:02.533763+02:00[Europe/Berlin]")
public class UpdatePackage {
  public static final String SERIALIZED_NAME_BINARY_ARCH = "BinaryArch";
  @SerializedName(SERIALIZED_NAME_BINARY_ARCH)
  private String binaryArch;

  public static final String SERIALIZED_NAME_BINARY_CHECKSUM = "BinaryChecksum";
  @SerializedName(SERIALIZED_NAME_BINARY_CHECKSUM)
  private String binaryChecksum;

  public static final String SERIALIZED_NAME_BINARY_HASH_TYPE = "BinaryHashType";
  @SerializedName(SERIALIZED_NAME_BINARY_HASH_TYPE)
  private String binaryHashType;

  public static final String SERIALIZED_NAME_BINARY_O_S = "BinaryOS";
  @SerializedName(SERIALIZED_NAME_BINARY_O_S)
  private String binaryOS;

  public static final String SERIALIZED_NAME_BINARY_SIGNATURE = "BinarySignature";
  @SerializedName(SERIALIZED_NAME_BINARY_SIGNATURE)
  private String binarySignature;

  public static final String SERIALIZED_NAME_BINARY_SIZE = "BinarySize";
  @SerializedName(SERIALIZED_NAME_BINARY_SIZE)
  private String binarySize;

  public static final String SERIALIZED_NAME_BINARY_U_R_L = "BinaryURL";
  @SerializedName(SERIALIZED_NAME_BINARY_U_R_L)
  private String binaryURL;

  public static final String SERIALIZED_NAME_CHANGE_LOG = "ChangeLog";
  @SerializedName(SERIALIZED_NAME_CHANGE_LOG)
  private String changeLog;

  public static final String SERIALIZED_NAME_DESCRIPTION = "Description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  private String description;

  public static final String SERIALIZED_NAME_IS_PATCH = "IsPatch";
  @SerializedName(SERIALIZED_NAME_IS_PATCH)
  private Boolean isPatch;

  public static final String SERIALIZED_NAME_LABEL = "Label";
  @SerializedName(SERIALIZED_NAME_LABEL)
  private String label;

  public static final String SERIALIZED_NAME_LICENSE = "License";
  @SerializedName(SERIALIZED_NAME_LICENSE)
  private String license;

  public static final String SERIALIZED_NAME_PACKAGE_NAME = "PackageName";
  @SerializedName(SERIALIZED_NAME_PACKAGE_NAME)
  private String packageName;

  public static final String SERIALIZED_NAME_PATCH_ALGORITHM = "PatchAlgorithm";
  @SerializedName(SERIALIZED_NAME_PATCH_ALGORITHM)
  private String patchAlgorithm;

  public static final String SERIALIZED_NAME_RELEASE_DATE = "ReleaseDate";
  @SerializedName(SERIALIZED_NAME_RELEASE_DATE)
  private Integer releaseDate;

  public static final String SERIALIZED_NAME_SERVICE_NAME = "ServiceName";
  @SerializedName(SERIALIZED_NAME_SERVICE_NAME)
  private String serviceName;

  public static final String SERIALIZED_NAME_STATUS = "Status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  private PackagePackageStatus status = PackagePackageStatus.DRAFT;

  public static final String SERIALIZED_NAME_VERSION = "Version";
  @SerializedName(SERIALIZED_NAME_VERSION)
  private String version;

  public UpdatePackage() { 
  }

  public UpdatePackage binaryArch(String binaryArch) {
    
    this.binaryArch = binaryArch;
    return this;
  }

   /**
   * Get binaryArch
   * @return binaryArch
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getBinaryArch() {
    return binaryArch;
  }


  public void setBinaryArch(String binaryArch) {
    this.binaryArch = binaryArch;
  }


  public UpdatePackage binaryChecksum(String binaryChecksum) {
    
    this.binaryChecksum = binaryChecksum;
    return this;
  }

   /**
   * Get binaryChecksum
   * @return binaryChecksum
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getBinaryChecksum() {
    return binaryChecksum;
  }


  public void setBinaryChecksum(String binaryChecksum) {
    this.binaryChecksum = binaryChecksum;
  }


  public UpdatePackage binaryHashType(String binaryHashType) {
    
    this.binaryHashType = binaryHashType;
    return this;
  }

   /**
   * Get binaryHashType
   * @return binaryHashType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getBinaryHashType() {
    return binaryHashType;
  }


  public void setBinaryHashType(String binaryHashType) {
    this.binaryHashType = binaryHashType;
  }


  public UpdatePackage binaryOS(String binaryOS) {
    
    this.binaryOS = binaryOS;
    return this;
  }

   /**
   * Get binaryOS
   * @return binaryOS
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getBinaryOS() {
    return binaryOS;
  }


  public void setBinaryOS(String binaryOS) {
    this.binaryOS = binaryOS;
  }


  public UpdatePackage binarySignature(String binarySignature) {
    
    this.binarySignature = binarySignature;
    return this;
  }

   /**
   * Get binarySignature
   * @return binarySignature
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getBinarySignature() {
    return binarySignature;
  }


  public void setBinarySignature(String binarySignature) {
    this.binarySignature = binarySignature;
  }


  public UpdatePackage binarySize(String binarySize) {
    
    this.binarySize = binarySize;
    return this;
  }

   /**
   * Get binarySize
   * @return binarySize
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getBinarySize() {
    return binarySize;
  }


  public void setBinarySize(String binarySize) {
    this.binarySize = binarySize;
  }


  public UpdatePackage binaryURL(String binaryURL) {
    
    this.binaryURL = binaryURL;
    return this;
  }

   /**
   * Get binaryURL
   * @return binaryURL
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getBinaryURL() {
    return binaryURL;
  }


  public void setBinaryURL(String binaryURL) {
    this.binaryURL = binaryURL;
  }


  public UpdatePackage changeLog(String changeLog) {
    
    this.changeLog = changeLog;
    return this;
  }

   /**
   * Get changeLog
   * @return changeLog
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getChangeLog() {
    return changeLog;
  }


  public void setChangeLog(String changeLog) {
    this.changeLog = changeLog;
  }


  public UpdatePackage description(String description) {
    
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getDescription() {
    return description;
  }


  public void setDescription(String description) {
    this.description = description;
  }


  public UpdatePackage isPatch(Boolean isPatch) {
    
    this.isPatch = isPatch;
    return this;
  }

   /**
   * Get isPatch
   * @return isPatch
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getIsPatch() {
    return isPatch;
  }


  public void setIsPatch(Boolean isPatch) {
    this.isPatch = isPatch;
  }


  public UpdatePackage label(String label) {
    
    this.label = label;
    return this;
  }

   /**
   * Get label
   * @return label
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getLabel() {
    return label;
  }


  public void setLabel(String label) {
    this.label = label;
  }


  public UpdatePackage license(String license) {
    
    this.license = license;
    return this;
  }

   /**
   * Get license
   * @return license
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getLicense() {
    return license;
  }


  public void setLicense(String license) {
    this.license = license;
  }


  public UpdatePackage packageName(String packageName) {
    
    this.packageName = packageName;
    return this;
  }

   /**
   * Get packageName
   * @return packageName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getPackageName() {
    return packageName;
  }


  public void setPackageName(String packageName) {
    this.packageName = packageName;
  }


  public UpdatePackage patchAlgorithm(String patchAlgorithm) {
    
    this.patchAlgorithm = patchAlgorithm;
    return this;
  }

   /**
   * Get patchAlgorithm
   * @return patchAlgorithm
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getPatchAlgorithm() {
    return patchAlgorithm;
  }


  public void setPatchAlgorithm(String patchAlgorithm) {
    this.patchAlgorithm = patchAlgorithm;
  }


  public UpdatePackage releaseDate(Integer releaseDate) {
    
    this.releaseDate = releaseDate;
    return this;
  }

   /**
   * Get releaseDate
   * @return releaseDate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getReleaseDate() {
    return releaseDate;
  }


  public void setReleaseDate(Integer releaseDate) {
    this.releaseDate = releaseDate;
  }


  public UpdatePackage serviceName(String serviceName) {
    
    this.serviceName = serviceName;
    return this;
  }

   /**
   * Get serviceName
   * @return serviceName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getServiceName() {
    return serviceName;
  }


  public void setServiceName(String serviceName) {
    this.serviceName = serviceName;
  }


  public UpdatePackage status(PackagePackageStatus status) {
    
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public PackagePackageStatus getStatus() {
    return status;
  }


  public void setStatus(PackagePackageStatus status) {
    this.status = status;
  }


  public UpdatePackage version(String version) {
    
    this.version = version;
    return this;
  }

   /**
   * Get version
   * @return version
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getVersion() {
    return version;
  }


  public void setVersion(String version) {
    this.version = version;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdatePackage updatePackage = (UpdatePackage) o;
    return Objects.equals(this.binaryArch, updatePackage.binaryArch) &&
        Objects.equals(this.binaryChecksum, updatePackage.binaryChecksum) &&
        Objects.equals(this.binaryHashType, updatePackage.binaryHashType) &&
        Objects.equals(this.binaryOS, updatePackage.binaryOS) &&
        Objects.equals(this.binarySignature, updatePackage.binarySignature) &&
        Objects.equals(this.binarySize, updatePackage.binarySize) &&
        Objects.equals(this.binaryURL, updatePackage.binaryURL) &&
        Objects.equals(this.changeLog, updatePackage.changeLog) &&
        Objects.equals(this.description, updatePackage.description) &&
        Objects.equals(this.isPatch, updatePackage.isPatch) &&
        Objects.equals(this.label, updatePackage.label) &&
        Objects.equals(this.license, updatePackage.license) &&
        Objects.equals(this.packageName, updatePackage.packageName) &&
        Objects.equals(this.patchAlgorithm, updatePackage.patchAlgorithm) &&
        Objects.equals(this.releaseDate, updatePackage.releaseDate) &&
        Objects.equals(this.serviceName, updatePackage.serviceName) &&
        Objects.equals(this.status, updatePackage.status) &&
        Objects.equals(this.version, updatePackage.version);
  }

  @Override
  public int hashCode() {
    return Objects.hash(binaryArch, binaryChecksum, binaryHashType, binaryOS, binarySignature, binarySize, binaryURL, changeLog, description, isPatch, label, license, packageName, patchAlgorithm, releaseDate, serviceName, status, version);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdatePackage {\n");
    sb.append("    binaryArch: ").append(toIndentedString(binaryArch)).append("\n");
    sb.append("    binaryChecksum: ").append(toIndentedString(binaryChecksum)).append("\n");
    sb.append("    binaryHashType: ").append(toIndentedString(binaryHashType)).append("\n");
    sb.append("    binaryOS: ").append(toIndentedString(binaryOS)).append("\n");
    sb.append("    binarySignature: ").append(toIndentedString(binarySignature)).append("\n");
    sb.append("    binarySize: ").append(toIndentedString(binarySize)).append("\n");
    sb.append("    binaryURL: ").append(toIndentedString(binaryURL)).append("\n");
    sb.append("    changeLog: ").append(toIndentedString(changeLog)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    isPatch: ").append(toIndentedString(isPatch)).append("\n");
    sb.append("    label: ").append(toIndentedString(label)).append("\n");
    sb.append("    license: ").append(toIndentedString(license)).append("\n");
    sb.append("    packageName: ").append(toIndentedString(packageName)).append("\n");
    sb.append("    patchAlgorithm: ").append(toIndentedString(patchAlgorithm)).append("\n");
    sb.append("    releaseDate: ").append(toIndentedString(releaseDate)).append("\n");
    sb.append("    serviceName: ").append(toIndentedString(serviceName)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

